compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

yarnPath: .yarn/releases/yarn-4.5.3.cjs

packageExtensions:
  "@storybook/core-common@*":
    dependencies:
      "webpack": "^5.0.0"
      "@storybook/react-webpack5": "^7.2.2"
